### ISSUE TITLE
move from pull to push model for policy data

### ISSUE THREAD

**Issue by chicco785** [orchestracities/anubis#14]
**Is your feature request related to a problem? Please describe.**

Currently policy data are pulled from the rego policies, this may create performance issues.

**Describe the solution you'd like**

When a policy is created or modified the auth api generates a payload to the opa data api. This data are then used to evaluate policies.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Cerfoglg** [comment]
Closing this, as this was implemented. Issue #196 exists to track further performance optimisation.
