### ISSUE TITLE
log: /etc/envoy/lua/common.lua:34: attempt to index a nil value

### ISSUE THREAD

**Issue by SURAJKALLOLI** [orchestracities/anubis#185]
Hi,
When i try to test the policy of create entity with valid token getting weired error that [error][lua] [source/extensions/filters/http/lua/lua_filter.cc:801] script log: /etc/envoy/lua/common.lua:34: attempt to index a nil value

**Comment by chicco785** [comment]
thx @SURAJKALLOLI, can you provide the data set-up you used to produce the error?

**Comment by SURAJKALLOLI** [comment]
> thx @SURAJKALLOLI, can you provide the data set-up you used to produce the error?

A clear and concise description of what the bug is.
When i try to create an entity with/without authorization with below data
 curl -s -i -X POST 'http://localhost:8000/v2/entities' \
-H 'Content-Type: application/json' \
-H 'fiware-Service: Tenant1' \
-H 'fiware-ServicePath: /' \
-d '{
      "id": "urn:ngsi-ld:AirQualityObserved:demo",
      "type": "AirQualityObserved",
      "temperature": {
        "type": "Number",
        "value": 12.2,
        "metadata": {}
      }
    }'
 it giving forbidden for both opertation even with valid token and when i checked the logs it showing  
log: /etc/envoy/lua/common.lua:34: attempt to index a nil value and i updated the keycloak user name admin to admin@mail.com in script file (file:run_demo.sh).

Expected output:
It should give 200 status code when i try to create entity.

**Comment by chicco785** [comment]
> > thx @SURAJKALLOLI, can you provide the data set-up you used to produce the error?
> 
> A clear and concise description of what the bug is. When i try to create an entity with/without authorization with below data curl -s -i -X POST 'http://localhost:8000/v2/entities' -H 'Content-Type: application/json' -H 'fiware-Service: Tenant1' -H 'fiware-ServicePath: /' -d '{ "id": "urn:ngsi-ld:AirQualityObserved:demo", "type": "AirQualityObserved", "temperature": { "type": "Number", "value": 12.2, "metadata": {} } }' it giving forbidden for both opertation even with valid token and when i checked the logs it showing log: /etc/envoy/lua/common.lua:34: attempt to index a nil value and i updated the keycloak user name from admin to [admin@mail.com](mailto:admin@mail.com) in script file (file:run_demo.sh).
> 
> Expected output: It should give 200 status code when i try to create entity.

are you using the up-to-date master version? user is already correct in the script on master:
https://github.com/orchestracities/anubis/blob/master/scripts/run_demo.sh#L58

can you let us know also the os you are using?

anyhow, we will try to reproduce with the information provided and come back to you.

**Comment by SURAJKALLOLI** [comment]
Yes i am using up to date master version only, 
-Linux (ubuntu 20.04) running on Azure VM.

Token generation for POST method to test the policy i am using this command 
curl -s -d "client_id=ngsi&client_secret=changeme&grant_type=password&username=admin@mail.com&password=admin" -X POST  'http://localhost:8080/realms/default/protocol/openid-connect/token

**Comment by chicco785** [comment]
```
anubis-front-envoy-1            | [2022-11-29 12:07:18.629][15][error][lua] [source/extensions/filters/http/lua/lua_filter.cc:801] script log: /etc/envoy/lua/common.lua:34: attempt to index a nil value
```
occurs only on requests where you don't pass a token. we can log better errors, but it make totally sense that without a token you cannot create a resource, also because on resource creation we identify the owner (from the token) and deploy ownership policies. clearly that cannot work without a jwt / oauth token.¨

so from my point of view when you don't pass the token, 403 is the correct answer.

how to obtain a token?

this is what we use:
```
export json=$(curl -s -d "client_id=ngsi&client_secret=changeme&grant_type=password&username=admin@mail.com&password=admin" -X POST --header "Host: keycloak:8080" 'http://localhost:8080/realms/default/protocol/openid-connect/token')
export token=$( jq -r ".access_token" <<<"$json" )
```

how to pass it to a request:

```
curl -s -o /dev/null -w "%{http_code}" --request POST 'http://localhost:8000/v2/entities' \
--header 'Content: application/json' \
--header 'fiware-Service: Tenant1' \
--header 'fiware-ServicePath: /' \
--header 'Content-Type: application/json' \
--header "Authorization: Bearer $token" \
--data-raw '{
  "id": "urn:ngsi-ld:AirQualityObserved:demo",
  "type": "AirQualityObserved",
  "temperature": {
    "type": "Number",
    "value": 12.2,
    "metadata": {}
  }
}'
```

i am going to test on a ubuntu (i have a mac), but I don't the os is the issue here, I think the requests you make may miss something.

**Comment by chicco785** [comment]
@SURAJKALLOLI 

is the vm an arm-based vm? do you see errors like:

```
8fc0b6cf12f8_8fc0b6cf12f8_8fc0b6cf12f8_anubis-ext_authz-opa-service-1  | exec ./opa_envoy_linux_amd64: exec format error
anubis-upstream-service-1                                              | exec /usr/bin/orionld: exec format error
```

then you need an x86 vm

**Comment by SURAJKALLOLI** [comment]
I pass the valid token only to create a the  resource but again i am getting reffer the screenshot,
![Screenshot (103)](https://user-images.githubusercontent.com/61748427/204725901-1074063b-0c7d-4779-ad51-48dd5d450a8e.png)
