### ISSUE TITLE
Integration with NGSI-LD/Scorpio broker

### ISSUE THREAD

**Issue by SURAJKALLOLI** [orchestracities/anubis#187]
Currently we are working with Scorpio broker/NGSI-ID instead of orion context broker , i am trying to  integrate Anubis with Scorpio broker , is it work if i just change the image of upstream-service from orion to scorpio/NGSI-LD in docker-compose file or You are still working with it or any suggestion!

**Comment by chicco785** [comment]
@SURAJKALLOLI I assume there is no much difference between Orion-LD and Scorpio in term of APIs. If that's the case, it's in the roadmap (#88)

**Comment by chicco785** [comment]
duplicates #88
