### ISSUE TITLE
design policy sharing middleware 

### ISSUE THREAD

**Issue by chicco785** [orchestracities/anubis#26]
**Is your feature request related to a problem? Please describe.**

Design a decentralised middleware supporting  the continuous governance of the policies and their synchronisation across different platforms leveraging a gossip-like protocol or alternative message exchange mechanisms.

**Describe the solution you'd like**

A document that guides the implementation of the middleware for policy sharing.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by chicco785** [comment]
Ideally we could use a decentralised message broker (e.g. https://nsq.io/) to run the following protocol:

1. when a new resource is registered in any of the services via anubi, a request for policies is issued to discover if the resource is already owned by someone and which policies are attached (this works under the assumption that resource identifier are "global").
2. if any of the anubi is the "source" of that entity, it returns the policies to the requester that stores them and subscribes to updates for that resource in the distributed queue. otherwise, the requester becomes the "source" of that entity.
---> here we need to be careful to what happens when the source anubi is offline, because then we create a new "source", i.e. a sort of brain split. clever ideas here?
3. if someone with `acl:control` access mode updates policies in any anubi instance, then a notification with update policies is sent across all the network.

in the specific use case of "orion" federations we need to think to a clever way to manage the synch of policies for entities created via notifications (which afaik don't go to /entities but to /op)

**Comment by chicco785** [comment]
@Cerfoglg please have a look and comments on the rough spec

**Comment by Cerfoglg** [comment]
Using a pub/sub type service is likely the best approach here. The one linked here seems like a good candidate if we want to avoid using any of the "bigger" ones.

As for the steps above:

1. If all of this is done by our proxy (envoy and opa) I'm starting to wonder if we should expand on it a bit, make it more an extra microservice to handle these operations. Just a thought.
2. The offline issue could be a bit tricky. We could just not permit the creation of new resources if a relevant anubi instance isn't reachable (and then figure out how to check for that), or just allow it and create a new source, and try to reconcile the sources afterwards, but that's not really good for security and consistency reasons. Speaking of consistency, that's something to be careful about, lest we end up with the instances out of sync.
3. Using the pub/sub system, then for every resource (or service path) we have a topic, then notifications for updates are sent out as messages and consumed by the various anubi to update themselves, if I understood this right. And like said above: with a system like this we need to be careful all remains in sync.

And as for orion federations, I assume we can employ the same logic we already have, but we also need to know who "owns" the resources that notifications create. Some extra metadata that needs to be included with them?

**Comment by chicco785** [comment]
create policy for a given resource (with p2p2 already registered to the topic):
```mermaid
sequenceDiagram
    participant anubis1
    participant p2p1
    participant p2p2
    participant anubis2
    anubis1->>p2p1: create policy
    p2p1->>p2p1: if topic does not exist, create it (e.g. /service/path/resourcetype/resorceid)
    p2p1->>p2p1: register as content provider for the topic
    p2p1->>p2p1: register to the topic
    p2p1->>p2p1: create policy message published on the topic
    p2p1->>p2p2: notify nodes registered to the topic
    p2p2->>anubis2: register policy
```

**Comment by chicco785** [comment]
create a new resource
```mermaid
sequenceDiagram
    participant anubis1
    participant p2p1
    participant p2p2
    participant anubis2
    anubis1->>p2p1: create resource
    p2p1->>p2p1: (if topic does not exist) create it (e.g. /service/path/resourcetype/resorceid)
    p2p1->>p2p1: (if topic does not exist) register as content provider for the topic
    p2p1->>p2p1: (if topic does not exist) register to the topic
    p2p1->>p2p1: (if topic exist) search content provider
    p2p1->>p2p2: (if topic exist) retrieve policies
    p2p2->>anubis2: (if topic exist) retrieve policies
    anubis2->>p2p2: (if topic exist) return policies
    p2p2->>p2p1: (if topic exist) return policies
    p2p1->>anubis1: (if topic exist) register policies
```
