### ISSUE TITLE
Resource owner

### ISSUE THREAD

**Issue by Cerfoglg** [orchestracities/anubis#42]
**Is your feature request related to a problem? Please describe.**

On resource creation, it should be possible to assign an "owner" to the resource (which is the subject who created the resource), and he should have full control on the resource, i.e. automatically a policy with "acl:control" should be created for him. anyhow this should happen only when the api ack that the resource was created (so that in case of failure the policy is not created).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chicco785** [comment]
@Cerfoglg of course this is not something you can do with authz filter.
most probably, the easiest way is creating a lua filter, see for example:
https://github.com/envoyproxy/envoy/tree/main/examples/lua
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter

on request you need to "filter" the requests to know if the action should be triggered, e.g. it must be a post to the path /entity, it must contain in the body "entityId"... ect this values can be also saved a metadata for reuse in the response.

then, on response, if status is 201 (i am guessing) and the values in metadata are correct ones, you issue a call to the api to trigger the creation of the policy. (probably this api is good for the purpose: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#httpcall)
